Repository smallrye/smallrye-mutiny, pull requests merged in 2020-10, with the labels that each got.

#315 Synchronize the ConnectableProcessor onComplete and onError to avoid race condition on state
  reactive-streams-operators/src/main/java/io/smallrye/mutiny/streams/utils/ConnectableProcessor.java
Labels: bug

#316 Mark spies as an experimental API
  implementation/pom.xml
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/Spy.java
  pom.xml
Labels: dependencies, enhancement

#323 Add support for onItem().failWith
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnCancellationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiSpyBase.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnItemFailWithTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemFailTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemFailWithTest.java
Labels: enhancement

#324 Uni.replaceWithNull and UniOnFailure.recoverWithNull
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRecoveryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java
Labels: enhancement

#325 Missing upstream cancellation on back pressure failure
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowBufferOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
Labels: bug

#327 Add tests verifying the correctness of inner merge and concat when the emission are done on different threads
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
Labels: enhancement

#329 Fix a race condition between onSubscribe / cancel / on{Item,Failure}
  implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
Labels: bug

#337 Avoid requesting individual items if the first request in requesting Long.MAX
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFilterOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiFilterTest.java
Labels: bug

#345 Fix Uni memoization infinite drain loop bug
  implementation/src/main/java/io/smallrye/mutiny/operators/UniMemoizeOp.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
Labels: bug
