Repository smallrye/smallrye-mutiny, pull requests merged in 2020-11, with the labels that each got.

#348 Fix potential invalid request (0) in the SkipOperator
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSkipOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSkipTest.java
Labels: bug

#349 onOverflow invoke / call
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflow.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflowStrategy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/queues/Queues.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnOverflowSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/Spy.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowBufferOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowDropItemsOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowKeepLastOp.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/spies/SpyTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
Labels: enhancement

#355 Generator-based Multi builder
  implementation/src/main/java/io/smallrye/mutiny/groups/GeneratorEmitter.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/GeneratorBasedMulti.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromGeneratorTest.java
  implementation/src/test/java/tck/MultiFromGeneratorTckTest.java
Labels: enhancement

#351 Implement batching with maximumDelay
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiGroupIntoLists.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
Labels: enhancement

#357 Various cleanups
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/CollectionBasedMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/IntervalMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/IterableBasedMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/StreamBasedMulti.java
Labels: technical-debt

#370 Clarify what happens when the supplier is null
  implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
Labels: documentation

#371 SafeSubscriber: move the upstream subscription to a regular field
  implementation/src/main/java/io/smallrye/mutiny/subscription/SafeSubscriber.java
Labels: technical-debt

#372 HalfSerializer onNext(): simplify the entry condition
  implementation/src/main/java/io/smallrye/mutiny/helpers/HalfSerializer.java
Labels: technical-debt

#373 Allow Multi creation from publishers that are assumed to be TCK-compliant
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromPublisherTest.java
Labels: enhancement

#374 Optimize MultiFilterOp on the hot path
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFilterOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiFilterTest.java
Labels: technical-debt
