Repository smallrye/smallrye-mutiny, pull requests merged in 2020-09, with the labels that each got.

#278 Fix a race condition and error propagation in UniSerializedSubscriber
  implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniSerializedSubscriberTest.java
Labels: bug

#283 Fix for #280
  context-propagation/src/test/java/io/smallrye/mutiny/context/MultiContextPropagationTest.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
Labels: bug

#268 Use Moditect to generate package-info for the main Mutiny module
  implementation/pom.xml
  implementation/src/main/module/module-info.java
  pom.xml
Labels: on-roadmap

#300 Revert a change made in 0.8.0 around the onOverflow().drop() operator
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowDropItemsOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
  implementation/src/test/java/tck/MultiOnOverflowDropTckTest.java
Labels: bug

#303 Deprecate MultiOnEvent and UniOnEvent
  documentation/src/main/docs/philosophy.adoc
  documentation/src/test/java/snippets/HowToJoinAsyncTest.java
  documentation/src/test/java/snippets/StageTest.java
  documentation/src/test/java/snippets/UniMultiComparisonTest.java
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
Labels: enhancement

#302 UniRetry and MultiRetry now tests the predicate from onFailure()
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
Labels: enhancement

#304 Support for custom Uni/Multi operators
  documentation/src/main/docs/faq.adoc
  documentation/src/test/java/snippets/PlugTest.java
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiPlugTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniPlugTest.java
Labels: enhancement

#306 Spies
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiGlobalSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnCancellationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnCompletionSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnFailureSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnItemSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnRequestSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnSubscribeSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnTerminationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiSpyBase.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/Spy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniGlobalSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnCancellationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnFailureSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnItemOrFailureSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnItemSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnSubscribeSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnTerminationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniSpyBase.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/spies/SpyTest.java
Labels: enhancement

#310 Make item collection optional in MultiOnItemSpy
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnItemSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/Spy.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/spies/SpyTest.java
Labels: enhancement

#311 New Uni.replaceWith shortcuts
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java
Labels: enhancement
