Repository smallrye/smallrye-mutiny, pull requests merged in 2020-12, with the labels that each got.

#376 Fix documentation typos
  documentation/src/main/docs/faq.adoc
  documentation/src/main/docs/getting-started.adoc
  documentation/src/main/docs/index.adoc
  documentation/src/main/docs/intro.adoc
  documentation/src/main/docs/philosophy.adoc
Labels: documentation

#378 Do not trigger onCancellation() when the stream has already completed
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCancellationCall.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCancellationInvoke.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnCancellationCallTest.java
Labels: enhancement

#379 Refactor to UniSubscriber
  context-propagation/src/main/java/io/smallrye/mutiny/context/ContextPropagationUniInterceptor.java
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniGlobalSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnCancellationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnFailureSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnItemOrFailureSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnItemSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnSubscribeSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/UniOnTerminationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniAndCombination.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromCompletionStage.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromDeferredSupplier.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateFromPublisher.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniCreateWithEmitter.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniDelayOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniDelayUntil.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniDelegatingSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniEmitOn.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniFailOnTimeout.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniMemoizeOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniNever.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnCancellation.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnCancellationCall.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnFailureFlatMap.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnFailureTransform.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemConsume.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemOrFailureConsume.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemOrFailureFlatMap.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMap.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemTransform.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemTransformToUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnSubscribeCall.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnSubscribeInvoke.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnTermination.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnTerminationCall.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOrCombination.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniRetryAtMost.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniRunSubscribeOn.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/KnownFailureUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/KnownItemUni.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/UniInterceptorTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniPlugTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniSerializedSubscriberTest.java
  reactor/revapi.json
  rxjava/revapi.json
Labels: technical-debt

#382 Remove UniSerializedSubscriber isCancelledOrDone
  implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
Labels: technical-debt

#385 Specialised Uni from item builders
  implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/StateSuppliedtemUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/SuppliedtemUni.java
Labels: technical-debt

#386 Fix potential deadlock in the SwitchableSubscriptionSubscriber
  implementation/src/main/java/io/smallrye/mutiny/subscription/SwitchableSubscriptionSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
Labels: bug

#393 Very minor typo in getting started guide
  documentation/src/main/jekyll/getting-started/transforming-items-async.adoc
Labels: documentation

#398 Clarify and verify the semantic of the combination, merge and concatenation of none or one upstream.
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiConcat.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreateBy.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiItemCombination.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiMerge.java
  implementation/src/main/java/io/smallrye/mutiny/operators/MultiCombine.java
  implementation/src/main/java/io/smallrye/mutiny/operators/MultiItemCombineIterable.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCombineTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiConcatTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiMergeTest.java
Labels: enhancement

#400 Write a getting started guide about events, invoke and call
  documentation/src/main/jekyll/_data/categories.yml
  documentation/src/main/jekyll/_data/guides.yml
  documentation/src/main/jekyll/_sass/asciidoc.scss
  documentation/src/main/jekyll/_sass/table.scss
  documentation/src/main/jekyll/assets/css/main.scss
  documentation/src/main/jekyll/assets/images/event-call.png
  documentation/src/main/jekyll/assets/images/event-invoke.png
  documentation/src/main/jekyll/getting-started/observing-events.adoc
  documentation/src/test/java/guides/ObserveTest.java
Labels: documentation

#401 Upgrade the website version on release
  .build/deploy.sh
Labels: enhancement

#402 Fix the website deployment
  .build/deploy-site.sh
  .build/deploy.sh
  .github/workflows/deployment.yml
Labels: bug

#407 Fix typo in documentation
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
Labels: documentation

#410 Fix UniCreate.deferred Javadoc
  implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
Labels: documentation
