Repository smallrye/smallrye-mutiny, pull requests merged in 2020-06, with the labels that each got.

#168 Improve safe subscriber
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
  implementation/src/main/java/io/smallrye/mutiny/subscription/SafeSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/SafeSubscriberTest.java
Labels: bug

#167 Fix Uni.or - The list didn't include the upstream Uni.
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOr.java
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/MultiInterceptor.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/MultiInterceptorTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/UniSubscriptionTest.java
  reactive-streams-operators/src/test/java/tck/ReactiveStreamsEngineImplTck.java
Labels: bug

#171 Add expireAt/expireIn to back off retry
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/ExponentialBackoff.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/MutinySchedulerTest.java
Labels: enhancement

#180 Add support for repeat whilst
  documentation/src/main/docs/faq.adoc
  documentation/src/test/java/snippets/PaginationTest.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatWhilstOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
  implementation/src/test/java/tck/UniRepeatWhilstTckTest.java
Labels: enhancement

#187 Uni.onFailure().invoke should enforce the failure predicate
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemConsume.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
Labels: bug

#185 Add onItem() / onFailure() invokeUni
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemIgnore.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemOrFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnItemFlatMap.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureInvokeUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRecoveryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnNotNullItemTest.java
  implementation/src/test/java/tck/MultiOnFailureInvokeTckTest.java
  implementation/src/test/java/tck/MultiOnFailureInvokeUniTckTest.java
  implementation/src/test/java/tck/MultiOnItemInvokeTckTest.java
  implementation/src/test/java/tck/MultiOnItemInvokeUniTckTest.java
Labels: enhancement

#188 Improve CompositeException to override getCause()
  implementation/src/main/java/io/smallrye/mutiny/CompositeException.java
  implementation/src/test/java/io/smallrye/mutiny/CompositeExceptionTest.java
Labels: enhancement

#194 Deprecate Uni.and / Uni.or
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java
Labels: enhancement, on-roadmap
