Repository smallrye/smallrye-mutiny, pull requests merged in 2020-07, with the labels that each got.

#196 Rename Uni/Multi apply to transform
  documentation/src/main/docs/faq.adoc
  documentation/src/test/java/snippets/BroadcastProcessorTest.java
  documentation/src/test/java/snippets/FlatMapTest.java
  documentation/src/test/java/snippets/GettingStarted.java
  documentation/src/test/java/snippets/HowToTransformTest.java
  documentation/src/test/java/snippets/MultiFailureTest.java
  documentation/src/test/java/snippets/RunSubscriptionOnTest.java
  documentation/src/test/java/snippets/ThenTest.java
  documentation/src/test/java/snippets/UniBlockingTest.java
  documentation/src/test/java/snippets/UniMultiComparisonTest.java
  documentation/src/test/java/snippets/UniNullTest.java
  documentation/src/test/java/snippets/UnicastProcessorTest.java
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemOrFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
  implementation/src/test/java/io/smallrye/mutiny/MultiThenTest.java
  implementation/src/test/java/io/smallrye/mutiny/UniThenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiConcatTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiIgnoreTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiMergeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureMapToTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRecoveryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMapTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnNotNullItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceTest.java
  implementation/src/test/java/tck/MultiFromResourceTckTest.java
Labels: enhancement

#198 Improve flaky tests in io.smallrye.mutiny.operators.MultiCreateFromTimePeriodTest
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
Labels: bug

#197 Deprecate Uni/Multi 'then' in favor of 'stage'
  documentation/src/main/docs/philosophy.adoc
  documentation/src/test/java/snippets/ThenTest.java
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/test/java/io/smallrye/mutiny/MultiStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/UniStageTest.java
Labels: enhancement

#195 Add the onSubscribe group to both Uni and Multi
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnCompletion.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnSubscribe.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnSubscribe.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnSubscribeInvoke.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnSubscribeInvokeUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnSubscription.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnSubscribeInvokeOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnSubscribeInvokeUniOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOperatorProcessor.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSignalConsumerOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSubscribeOnOp.java
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiFlattenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAssertSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceTest.java
  implementation/src/test/java/tck/MultiOnSubscribeInvokeTckTest.java
  implementation/src/test/java/tck/MultiOnSubscribeInvokeUniTckTest.java
  test-utils/src/main/java/io/smallrye/mutiny/test/MultiAssertSubscriber.java
Labels: enhancement

#183 Reduce duplication between the 2 MultiRepeat operators
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatWhilstOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiToHotStreamTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/BroadcastProcessorTest.java
Labels: enhancement

#205 Add eventually methods to Uni
  documentation/src/main/docs/faq.adoc
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
Labels: enhancement

#210 Remove traces from the MultiOnSubscribeInvokeUniOp
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnSubscribeInvokeUniOp.java
Labels: bug

#211 Remove termination handling from MultiSignalConsumerOp
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnCompletion.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSignalConsumerOp.java
Labels: enhancement

#219 Fix out-of-order headings in documentation
  documentation/src/main/docs/faq.adoc
  documentation/src/main/docs/getting-started.adoc
  documentation/src/main/docs/intro.adoc
  documentation/src/main/docs/philosophy.adoc
  documentation/src/test/java/snippets/EventsTest.java
Labels: documentation

#218 Add Uni.onItem().disjoint()
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDisjointTest.java
Labels: enhancement

#222 Optimize Queue usages
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiFlatten.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/Subscriptions.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/queues/EmptyQueue.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/queues/Queues.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/queues/SingletonQueue.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiEmitOnOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiGroupByOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiWindowOnDurationOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiWindowOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiZipOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BufferItemMultiEmitter.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/SerializedMultiEmitter.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/multicast/MultiPublishOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowBufferOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessor.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/queues/QueuesTest.java
Labels: bug, enhancement

#226 Create onCancellation() groups for Uni and Multi
  documentation/src/test/java/snippets/EventsTest.java
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnCancel.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnCancel.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniOnCancellationInvokeUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCancellationInvoke.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCancellationInvokeUni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnCancellationInvokeUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnTerminationUniInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniToMultiTest.java
Labels: enhancement

#228 Multi.onCompletion() invoke and invokeUni
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnCompletion.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCompletionInvoke.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCompletionInvokeUni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnCompletionTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnTerminationUniInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiReceiveItemOnTest.java
  implementation/src/test/java/tck/MultiOnCancellationInvokeTckTest.java
  implementation/src/test/java/tck/MultiOnCancellationInvokeUniTckTest.java
  implementation/src/test/java/tck/MultiOnCompletionInvokeTckTest.java
  implementation/src/test/java/tck/MultiOnCompletionInvokeUniTckTest.java
Labels: enhancement

#233 Harmonize group access
  documentation/src/test/java/snippets/EventsTest.java
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnRequest.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnRequestInvoke.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnRequestInvokeUni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnRequestTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnTerminationUniInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
  implementation/src/test/java/tck/MultiOnRequestInvokeTckTest.java
  implementation/src/test/java/tck/MultiOnRequestInvokeUniTckTest.java
Labels: enhancement

#238 Increase test coverage in MultiTransformToUniTest
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToUniTest.java
Labels: enhancement
