Repository smallrye/smallrye-mutiny, pull requests merged in 2021-02, with the labels that each got.

#467 Add a BOM to Mutiny
  bom/pom.xml
  documentation/src/main/jekyll/getting-started/download.adoc
  pom.xml
Labels: enhancement

#471 Fix a bug when Uni from JDK Future get cancelled
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFuture.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromFutureTest.java
Labels: bug

#472 Uni and Multi log operators
  documentation/pom.xml
  documentation/src/main/jekyll/_data/categories.yml
  documentation/src/main/jekyll/_data/guides.yml
  documentation/src/main/jekyll/guides/logging.adoc
  documentation/src/test/java/guides/infrastructure/OperatorLoggingTest.java
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiLogger.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniLogger.java
  implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniAndMultiLoggerTest.java
  implementation/src/test/java/tck/MultiLoggerTckTest.java
Labels: enhancement

#479 Fix doc typos
  documentation/src/main/jekyll/_layouts/index.html
  documentation/src/main/jekyll/pages/philosophy.adoc
  documentation/src/test/java/guides/EventsTest.java
Labels: documentation

#480 Fix doc typos
  documentation/src/main/jekyll/_data/guides.yml
  documentation/src/main/jekyll/getting-started/transforming-items-async.adoc
  documentation/src/main/jekyll/guides/collecting-items.adoc
  documentation/src/main/jekyll/guides/combining-items.adoc
  documentation/src/main/jekyll/guides/completion-stages.adoc
  documentation/src/main/jekyll/guides/filter.adoc
  documentation/src/main/jekyll/guides/imperative-to-reactive.adoc
  documentation/src/main/jekyll/guides/merge-concat.adoc
  documentation/src/main/jekyll/guides/reactive-to-imperative.adoc
  documentation/src/main/jekyll/guides/repetitions.adoc
  documentation/src/main/jekyll/guides/rx.adoc
  documentation/src/main/jekyll/guides/take-skip.adoc
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
Labels: documentation

#485 Implement Multi.createFrom().emitter(Consumer, int buffSize)
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BaseMultiEmitter.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/BufferItemMultiEmitter.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMulti.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromEmitterTest.java
Labels: enhancement

#487 Uni.replaceWithVoid
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java
Labels: enhancement

#489 Add Uni.createFrom().resourceFromUni
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiResourceUni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceFromUniTest.java
Labels: enhancement
