Repository smallrye/smallrye-mutiny, pull requests merged in 2021-05, with the labels that each got.

#545 Fix NPE
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnFailureInvoke.java
Labels: bug

#546 Upgrade RevAPI dependencies
  pom.xml
Labels: dependencies

#551 Another round of RevAPI upgrades
  pom.xml
Labels: dependencies

#552 Use the Google Mirror as an additional repository in all CI tasks
  .build/cut-release.sh
  .build/deploy-site.sh
  .build/maven-ci-settings.xml
  .build/maven-settings.xml.gpg
  .github/workflows/build-main.yml
  .github/workflows/build-pull.yml
Labels: ci/cd

#521 Deprecated APIs removal batch
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnCancel.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnCompletion.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnRequest.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnSubscribe.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnTerminate.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniCombine.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnCancel.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnEvent.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnItemOrFailure.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnSubscribe.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnTerminate.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOrCombination.java
  implementation/src/test/java/io/smallrye/mutiny/MultiStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/UniStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiConcatTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiMergeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnCancellationCallTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnCompletionTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureCallTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnItemCallTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnRequestTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnTerminationUniInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiToUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDisjointTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureFlatMapTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMapTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemProduceCompletionStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToUniWithEmitterTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnNotNullItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java
  implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedFunctionTest.java
Labels: on-roadmap, technical-debt

#554 ✨ Revamped README
  README.adoc
Labels: documentation, enhancement

#558 Convenience combinedWith method with a class cast
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroupIterable.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
Labels: enhancement

#565 Link to GitHub discussions
  documentation/src/main/jekyll/_includes/header-navigation.html
Labels: documentation

#553 Implement mathematical operators
  bom/pom.xml
  math/README.md
  math/pom.xml
  math/revapi.json
  math/src/main/java/io/smallrye/mutiny/math/AverageOperator.java
  math/src/main/java/io/smallrye/mutiny/math/CountOperator.java
  math/src/main/java/io/smallrye/mutiny/math/IndexOperator.java
  math/src/main/java/io/smallrye/mutiny/math/Math.java
  math/src/main/java/io/smallrye/mutiny/math/MaxOperator.java
  math/src/main/java/io/smallrye/mutiny/math/MedianOperator.java
  math/src/main/java/io/smallrye/mutiny/math/MinOperator.java
  math/src/main/java/io/smallrye/mutiny/math/OccurrenceOperator.java
  math/src/main/java/io/smallrye/mutiny/math/Statistic.java
  math/src/main/java/io/smallrye/mutiny/math/StatisticsOperator.java
  math/src/main/java/io/smallrye/mutiny/math/SumOperator.java
  math/src/main/java/io/smallrye/mutiny/math/TopOperator.java
  math/src/main/module/module-info.java
  math/src/test/java/io/smallrye/mutiny/math/AverageOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/AverageOperatorWithDoubleTest.java
  math/src/test/java/io/smallrye/mutiny/math/AverageOperatorWithIntegerTest.java
  math/src/test/java/io/smallrye/mutiny/math/CountOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/IndexOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/MaxOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/MedianOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/MinOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/OccurrenceOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/StatisticOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/SumOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/TopOperatorTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/AverageTckTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/CountOperatorTckTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/IndexOperatorTckTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/MaxOperatorTckTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/MedianTckTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/MinOperatorTckTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/StatisticsTckTest.java
  math/src/test/java/io/smallrye/mutiny/math/tck/TckHelper.java
  pom.xml
Labels: enhancement, noteworthy-feature

#566 Sonar Quality Gate fixes in math
  math/src/main/java/io/smallrye/mutiny/math/Math.java
  math/src/test/java/io/smallrye/mutiny/math/StatisticOperatorTest.java
Labels: technical-debt
