Repository smallrye/smallrye-mutiny, pull requests merged in 2021-01, with the labels that each got.

#412 Improve test utilities
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AbstractSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertionHelper.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/SerializedMultiEmitter.java
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiBroadcastTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AbstractSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMultiTest.java
Labels: enhancement

#414 Add helpers.{spies,test} and subscription packages in the module-info.java
  implementation/src/main/module/module-info.java
Labels: bug

#416 Add multi.collect().where(...) and multi.collect().when(...).
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCollect.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCollectTest.java
Labels: enhancement

#377 Internal optimisations
  implementation/src/main/java/io/smallrye/mutiny/converters/uni/ToPublisher.java
  implementation/src/main/java/io/smallrye/mutiny/converters/uni/UniToMultiPublisher.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/ParameterValidation.java
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFlatMapOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatWhilstOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/CollectionBasedMulti.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/ParameterValidationTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromEmitterTest.java
Labels: technical-debt

#428 Bump revapi versions
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/AbstractMultiOperator.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/AbstractMultiOperatorTest.java
  pom.xml
  reactor/revapi.json
  rxjava/revapi.json
Labels: technical-debt

#423 remove subscribeOn and configure revapi properly
  .build/GitBlameDeprecated.java
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiSkip.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiReceiveItemOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
  reactor/revapi.json
Labels: technical-debt

#419 Kotlin module
  documentation/pom.xml
  documentation/src/main/jekyll/_data/categories.yml
  documentation/src/main/jekyll/_data/guides.yml
  documentation/src/main/jekyll/guides/kotlin.adoc
  documentation/src/test/kotlin/guides/Coroutines.kt
  kotlin/pom.xml
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Util.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/DeferredAsUniTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/FlowAsMultiTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/UniAwaitSuspendingTest.kt
  pom.xml
Labels: enhancement, noteworthy-feature

#435 Update RevAPI
  pom.xml
Labels: technical-debt

#440 Maven POM descriptors cosmetics
  context-propagation/pom.xml
  documentation/pom.xml
  implementation/pom.xml
  kotlin/pom.xml
  pom.xml
  reactive-streams-junit5-tck/pom.xml
  reactive-streams-operators/pom.xml
  reactor/pom.xml
  release/pom.xml
  rxjava/pom.xml
  test-utils/pom.xml
Labels: documentation

#442 Iteration optimisations regarding Infrastructure's interceptors
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
Labels: enhancement

#443 Fix Uni subscription when interceptors are present
  implementation/src/main/java/io/smallrye/mutiny/operators/UniSerializedSubscriber.java
Labels: bug

#454 Fix repetition when the first emitted item is `null`
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
Labels: bug

#457 Add the ability to create a Uni from a Future or a Supplier of Future
  implementation/src/main/java/io/smallrye/mutiny/groups/UniCreate.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFuture.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromFutureTest.java
Labels: enhancement

#462 Explicitly cancel the scheduled future upon user's cancellation
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/IntervalMulti.java
Labels: bug

#464 Uni signals tracking and ordering assertion in UniAssertSubscriber
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnCancellationUniSignal.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnFailureUniSignal.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnItemUniSignal.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/OnSubscribeUniSignal.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniSignal.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriberTest.java
Labels: enhancement
