Repository smallrye/smallrye-mutiny, pull requests merged in 2021-12, with the labels that each got.

#755 test(kotlin): create test to cancel deferred
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/DeferredAsUniTest.kt
Labels: enhancement

#772 Update Kotlin and Dokka to 1.6.0
  pom.xml
Labels: dependencies, java

#769 Reduce tests flakiness, especially in CI / constrained environments
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiDisjointTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiEmitOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnItemFailWithTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureTransformTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMapTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniSubscribeAsCompletionStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniToPublisherTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessorTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/SerializedSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedConsumerTest.java
  implementation/src/test/java/junit5/support/AwaitilityConfigurationExtension.java
  implementation/src/test/resources/META-INF/services/org.junit.jupiter.api.extension.Extension
  implementation/src/test/resources/junit-platform.properties
Labels: technical-debt, ci/cd/build

#770 Parallel tests execution
  CONTRIBUTING.md
  implementation/pom.xml
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiTimePeriod.java
  implementation/src/test/java/io/smallrye/mutiny/BugReproducersTest.java
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiBroadcastTest.java
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiDisjointTest.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/BlockingIterableTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/CallbackDecoratorTest.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/DroppedExceptionsTest.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/MutinySchedulerTest.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/UniInterceptorTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiDistinctTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectFirstOrLastTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSkipTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTakeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAwaitTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromFutureTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnEventTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDelayTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDelayUntilTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureFlatMapTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnTerminationTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniSerializedSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniSubscribeAsCompletionStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiToHotStreamTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromIterableTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceFromUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/multicast/MultiReferenceCountSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/BroadcastProcessorTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniAndMultiLoggerTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/CallbackBasedSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/SafeSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/SerializedSubscriberTest.java
  implementation/src/test/java/junit5/support/InfrastructureResource.java
  implementation/src/test/java/tck/MultiLoggerTckTest.java
Labels: ci/cd/build
