Repository smallrye/smallrye-mutiny, pull requests merged in 2021-11, with the labels that each got.

#740 Check for emptiness when joining an empty set of Unis and extend Javadoc
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/ParameterValidation.java
  implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
Labels: documentation

#737 Add item timeouts to Multi
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiIfNoItem.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItemTimeout.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFailOnItemTimeout.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
Labels: enhancement

#754 Grouped dependencies updates
  documentation/pom.xml
  pom.xml
Labels: dependencies

#759 Fix and simplify Uni.join() parametric types
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiFailOnItemTimeout.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinAll.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinFirst.java
  implementation/src/test/java/io/smallrye/mutiny/BugReproducersTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/SerializedSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/unchecked/UncheckedConsumerTest.java
Labels: bug, enhancement

#750 Update documentation example
  documentation/src/main/jekyll/_layouts/index.html
Labels: documentation

#766 Maven profile to skip running the Reactive Streams TCK tests
  implementation/pom.xml
Labels: ci/cd

#768 Use a Maven wrapper
  .build/cut-release.sh
  .build/deploy-release.sh
  .build/deploy-snapshot.sh
  .github/workflows/build-main.yml
  .github/workflows/build-pull.yml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
  pom.xml
Labels: ci/cd
