Repository smallrye/smallrye-mutiny, pull requests merged in 2021-03, with the labels that each got.

#494 Enhance testing utilities
  context-propagation/src/test/java/io/smallrye/mutiny/context/MultiContextPropagationTest.java
  documentation/src/test/java/guides/operators/BroadcastProcessorTest.java
  documentation/src/test/java/guides/operators/UnicastProcessorTest.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnFailure.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/MultiOnCancellationSpy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertionHelper.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiBroadcastTest.java
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiDisjointTest.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AbstractSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCollectTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromCompletionStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiDistinctTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiEmitOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiReceiveItemOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectFirstOrLast.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSkipTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTakeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiToUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformByMergingTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniCreateFromFutureTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureTransformTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDelayTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemDelayUntilTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureFlatMapTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureInvokeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemOrFailureMapTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemProduceCompletionStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnItemTransformToUniWithEmitterTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnSubscribeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnTerminationTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOrTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRunSubscriptionOnTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniSerializedSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/EmitterBasedMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceFromUniTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/processors/SerializedProcessorTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/SerializedSubscriberTest.java
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/DeferredAsUniTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/FlowAsMultiTest.kt
Labels: enhancement

#498 Allow configuring a delay between two repetitions
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatUntilOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRepeatWhilstOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniRepeatTest.java
Labels: enhancement

#505 Configure CI to run the build with Java 15 and 16 (EA).
  .github/workflows/build-master.yml
  .github/workflows/build-pull.yml
Labels: technical-debt

#507 Fix a request / consume race when using .request(x).awaitNextItems(x)
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiEmitOnTest.java
Labels: bug

#511 Break dependency to mutiny-test-utils
  implementation/pom.xml
Labels: dependencies, technical-debt

#512 TCK: support TestNG SkipException
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
  reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/IdentityProcessorVerification.java
  reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/PublisherVerification.java
  reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/SubscriberBlackboxVerification.java
  reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/SubscriberWhiteboxVerification.java
  reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/TestngSkippingExtension.java
  reactive-streams-junit5-tck/src/test/java/org/reactivestreams/tck/junit5/TestngSkippingExtensionTest.java
Labels: bug, technical-debt

#515 Fix the post release scripts version extraction from tag
  .github/workflows/post-release.yml
Labels: ci/cd
