Repository smallrye/smallrye-mutiny, pull requests merged in 2021-04, with the labels that each got.

#520 Fix race condition when waiting for items in the MultiGroupTest
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
Labels: ci/cd

#526 New approach for the awaitItems method in the AssertSubscriber
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
Labels: bug

#484 Remove JCenter
  kotlin/pom.xml
  pom.xml
Labels: dependencies

#524 Fix duplicate items issue when create a multi from a collection
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/builders/CollectionBasedMulti.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromIterableTest.java
Labels: bug

#525 Multiple upstream requests in the multi.collect().last() operator
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiLastItemOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCollectTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectFirstOrLast.java
Labels: bug

#530 Change the default infrastructure pool to be a cached thread pool instead of the fork/join
  documentation/src/main/jekyll/guides/infrastructure.adoc
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
Labels: enhancement, technical-debt

#531 Fix incomplete AssertJ API usage
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCombineTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiConcatTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiMergeTest.java
Labels: bug

#534 Catch Throwable rather than RuntimeException
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniDelayOnItem.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniDelayUntil.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOnFailureTransform.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromCompletionStageWithState.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromDeferredSupplierWithState.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromEmitterWithState.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFailureSupplier.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromFuture.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromItemSupplier.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromItemWithState.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateWithEmitter.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/SneakyThrow.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromItemsTest.java
Labels: bug

#537 Release the downstream subscriber upon cancellation.
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiBufferWithTimeoutOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiCollectorOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiLastItemOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnItemInvoke.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOperatorProcessor.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSelectFirstWhileOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/overflow/MultiOnOverflowBufferOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniCreateFromPublisher.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCombineTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/builders/MultiFromResourceTest.java
Labels: bug, technical-debt
