Repository smallrye/smallrye-mutiny, pull requests merged in 2021-09, with the labels that each got.

#670 Allow disabling all Callback decorators via environment properties
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
Labels: enhancement

#678 Fix off-by-one retry count when using exponential backoff
  implementation/src/main/java/io/smallrye/mutiny/helpers/ExponentialBackoff.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRetryTest.java
Labels: bug

#695 Use Eclipse Temurin + 8/11/17 matrix
  .github/workflows/build-main.yml
  .github/workflows/build-pull.yml
  .github/workflows/deploy-release.yml
  .github/workflows/deploy-site.yml
  .github/workflows/post-release.yml
  .github/workflows/prepare-release.yml
  kotlin/pom.xml
Labels: ci/cd
