Repository smallrye/smallrye-mutiny, pull requests merged in 2021-07, with the labels that each got.

#606 Fix NPE happening after cancellation in MultiSelectFirstOp
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSelectFirstOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectFirstOrLastTest.java
Labels: bug

#604 New Uni join API
  documentation/src/main/jekyll/_data/categories.yml
  documentation/src/main/jekyll/_data/guides.yml
  documentation/src/main/jekyll/guides/joining-unis.adoc
  documentation/src/test/java/guides/operators/UniJoinTest.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinAll.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinFirst.java
  implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
Labels: enhancement

#611 Migrate to smallrye-build-parent and isolate BOM
  .github/workflows/build-main.yml
  .github/workflows/build-pull.yml
  bom/pom.xml
  context-propagation/pom.xml
  documentation/pom.xml
  implementation/pom.xml
  implementation/src/test/java/io/smallrye/mutiny/helpers/CausedTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromGeneratorTest.java
  kotlin/pom.xml
  math/pom.xml
  pom.xml
  reactive-streams-junit5-tck/pom.xml
  reactive-streams-operators/pom.xml
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/APITest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/CollectStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/DistinctStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/DropWhileStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/FilterStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/FindFirstStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/FlatMapCompletionStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/FlatMapIterableStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/FlatMapStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/LimitStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/MapStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/OnCompleteStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/OnErrorResumeWithStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/OnErrorStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/OnTerminateStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/PeekStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/ProcessorStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/SkipStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/SubscriberStageFactoryTest.java
  reactive-streams-operators/src/test/java/io/smallrye/mutiny/streams/stages/TakeWhileStageFactoryTest.java
  reactor/pom.xml
  rxjava/pom.xml
  test-utils/pom.xml
Labels: dependencies, enhancement

#567 Update Kotlin and Coroutines to 1.5
  pom.xml
Labels: dependencies

#631 Simplify Uni to Multi bridge
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/converters/uni/UniToMultiPublisher.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
Labels: enhancement, technical-debt

#632 Simplify Uni to Multi bridge (again)
  implementation/src/main/java/io/smallrye/mutiny/converters/uni/UniToMultiPublisher.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
Labels: enhancement, technical-debt

#627 Add failWith methods to UniOnNotNull
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnNotNull.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnNotNullItemTest.java
Labels: enhancement

#635 Use the thread-local ThreadContext in order to be able to define which contexts get propagated
  context-propagation/src/main/java/io/smallrye/mutiny/context/DefaultContextPropagationInterceptor.java
  context-propagation/src/main/java/io/smallrye/mutiny/context/MutinyContextManagerExtension.java
  context-propagation/src/test/java/io/smallrye/mutiny/context/MultiContextPropagationTest.java
  context-propagation/src/test/java/io/smallrye/mutiny/context/UniContextPropagationTest.java
Labels: enhancement

#636 Documentation for Uni.map incorrect
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
Labels: documentation

#639 Remove Java 15 from CI
  .github/workflows/build-main.yml
  .github/workflows/build-pull.yml
Labels: ci/cd

#643 Harmonize POM name / description sections
  bom/pom.xml
  context-propagation/pom.xml
  documentation/pom.xml
  implementation/pom.xml
  kotlin/pom.xml
  math/pom.xml
  pom.xml
  reactive-streams-junit5-tck/pom.xml
  reactive-streams-operators/pom.xml
  reactor/pom.xml
  release/pom.xml
  rxjava/pom.xml
  test-utils/pom.xml
Labels: technical-debt
