Repository smallrye/smallrye-mutiny, pull requests merged in 2021-06, with the labels that each got.

#577 Enforce API contract on UniCombine emptiness
  implementation/src/main/java/io/smallrye/mutiny/groups/UniZip.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
Labels: bug

#579 Math operators with concurrent data structures
  math/src/main/java/io/smallrye/mutiny/math/AverageOperator.java
  math/src/main/java/io/smallrye/mutiny/math/CountOperator.java
  math/src/main/java/io/smallrye/mutiny/math/IndexOperator.java
  math/src/main/java/io/smallrye/mutiny/math/MaxOperator.java
  math/src/main/java/io/smallrye/mutiny/math/MedianOperator.java
  math/src/main/java/io/smallrye/mutiny/math/MinOperator.java
  math/src/main/java/io/smallrye/mutiny/math/OccurrenceOperator.java
  math/src/main/java/io/smallrye/mutiny/math/Statistic.java
  math/src/main/java/io/smallrye/mutiny/math/StatisticsOperator.java
  math/src/main/java/io/smallrye/mutiny/math/SumOperator.java
  math/src/main/java/io/smallrye/mutiny/math/TopOperator.java
Labels: enhancement

#595 Implement Uni.replaceIfNullWith(value / supplier) shortcuts
  documentation/src/main/jekyll/guides/shortcuts.adoc
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniReplaceWithTest.java
Labels: enhancement

#601 Move JavaDoc for MultiOnItem.transformToUniAndConcatenate
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOnItem.java
Labels: documentation
