Repository smallrye/smallrye-mutiny, pull requests merged in 2022-11, with the labels that each got.

#1106 Kotlin - Enhance Multi.asFlow documentation with buffering note
  documentation/docs/guides/kotlin.md
Labels: documentation, Kotlin

#1113 Avoid type cache pollution on parameter validation in UniOperatorProcessor
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniOperatorProcessor.java
Labels: enhancement, technical-debt, backport

#1114 CI post-release minor fixes
  .github/workflows/post-release.yml
Labels: ci/cd/build

#1119 Document that UnicastProcessor cannot be re-subscribed
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/processors/UnicastProcessor.java
Labels: documentation, backport

#1121 Replace superfluous awaitility assertions in MultiIfNoItemTest
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
Labels: technical-debt

#1125 Warning about potential multi-threading issues when not using emitOn properly
  documentation/docs/guides/emission-threads.md
  documentation/docs/guides/emit-on-vs-run-subscription-on.md
  documentation/docs/guides/imperative-to-reactive.md
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
Labels: documentation

#1126 Reduce flakyness in MultiIfNoItemTest
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
Labels: ci/cd/build, internal

#1127 Documentation for migrating to Mutiny 2
  documentation/docs/reference/migrating-to-mutiny-2.md
  documentation/mkdocs.yml
Labels: documentation

#1128 Fix typo in Javadoc of UniCombine.any()
  implementation/src/main/java/io/smallrye/mutiny/groups/UniCombine.java
Labels: documentation

#1132 Just fix a typo in javadoc
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
Labels: documentation, backport

#1133 Align to Mutiny Zero 1.0.0
  pom.xml
Labels: dependencies
