Repository smallrye/smallrye-mutiny, pull requests merged in 2022-10, with the labels that each got.

#1064 Add Uni.replaceWithUnit and Uni builders to Kotlin module
  documentation/docs/guides/kotlin.md
  documentation/src/test/kotlin/guides/Coroutines.kt
  documentation/src/test/kotlin/guides/UniExt.kt
  kotlin/pom.xml
  kotlin/src/main/kotlin/io/smallrye/mutiny/UniExt.kt
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/UniBuilderTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/UniReplaceWithUnitTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/UniCoroutineBuilderTest.kt
Labels: enhancement, Kotlin

#1068 Fix validator typo
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiBufferOp.java
Labels: backport

#1077 Prefer .awaitXYZ() methods in documentation
  documentation/src/test/java/guides/TestSubscribersTest.java
Labels: documentation, backport

#1081 Hidden Subscription checkcast scalability issue (Fixes #1080)
  implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
Labels: enhancement

#1083 Hidden Subscription checkcast scalability issue (Fixes #1080)
  implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
Labels: enhancement, backport

#1093 Document the usage of spies (advanced guide)
  documentation/docs/guides/spies.md
  documentation/mkdocs.yml
  documentation/src/test/java/guides/SpiesTest.java
Labels: documentation, backport

#1092 Multi overflow unbounded strategy was actually bounded
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflow.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflowStrategy.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/InfrastructureTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
Labels: bug, documentation, backport

#1100 Reduce flaky tests by increasing timeouts in CI
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/BlockingIterableTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromTimePeriodTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiIfNoItemTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformToMultiTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAwaitTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniIfNoItemTest.java
  implementation/src/test/java/junit5/support/AwaitilityConfigurationExtension.java
  pom.xml
Labels: ci/cd/build

#1105 #1103 Refactor Multi.toFlow() to avoid blocking - Mutiny2
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt
Labels: bug, Kotlin
