Repository smallrye/smallrye-mutiny, pull requests merged in 2022-03, with the labels that each got.

#854 Run tests in random order
  implementation/pom.xml
Labels: ci/cd/build

#861 Add the ability not to clear certain versions
  .build/CompatibilityUtils.java
Labels: ci/cd/build

#863 Avoid overflow when using ChronoUnit.FOREVER with the memoize operator
  implementation/src/main/java/io/smallrye/mutiny/groups/UniMemoize.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
Labels: bug

#867 Document creating Multis from a generator
  documentation/src/main/jekyll/getting-started/creating-multis.adoc
  documentation/src/test/java/guides/CreatingMultiTest.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiReplay.java
Labels: documentation

#876 Add the missing CheckReturnValue annotations to the Multi replay operator API
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiReplay.java
Labels: bug

#875 New Multi demand pacing operator
  documentation/src/main/jekyll/_data/categories.yml
  documentation/src/main/jekyll/_data/guides.yml
  documentation/src/main/jekyll/guides/controlling-demand.adoc
  documentation/src/test/java/guides/operators/ControlDemandTest.java
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiDemandPacing.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDemandPacer.java
  implementation/src/main/java/io/smallrye/mutiny/subscription/DemandPacer.java
  implementation/src/main/java/io/smallrye/mutiny/subscription/FixedDemandPacer.java
  implementation/src/test/java/io/smallrye/mutiny/groups/MultiDemandPacingTest.java
  implementation/src/test/java/io/smallrye/mutiny/subscription/DemandPacerRequestTest.java
Labels: enhancement

#879 Misc fixes to .build/BlameAPI.java
  .build/BlameAPI.java
Labels: bug, ci/cd/build

#877 New experimental demand capping operators
  documentation/src/main/jekyll/guides/controlling-demand.adoc
  documentation/src/test/java/guides/operators/ControlDemandTest.java
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDemandCapping.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiDemandCappingTest.java
  reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiDemandCappingTckTest.java
Labels: enhancement

#882 Document the Git commit requirements
  CONTRIBUTING.md
Labels: documentation

#883 Move io.smallrye.mutiny.operators.multi.processors to the public API
  implementation/pom.xml
  implementation/revapi.json
  implementation/src/main/module/module-info.java
Labels: documentation

#884 Promote spies to a stable API
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/helpers/spies/Spy.java
Labels: api-promotion

#887 Fix the capping operators outstanding demand management
  documentation/src/main/jekyll/guides/controlling-demand.adoc
  documentation/src/test/java/guides/operators/ControlDemandTest.java
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiDemandCapping.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiDemandCappingTest.java
Labels: bug

#890 Use Maven 3.8.5
  .mvn/wrapper/maven-wrapper.properties
Labels: ci/cd/build
