Repository smallrye/smallrye-mutiny, pull requests merged in 2022-12, with the labels that each got.

#1138 Remove extra `onItem(1)` in documentation
  documentation/docs/guides/merging-and-concatenating-streams.md
Labels: documentation

#1142 When using Multi.createFrom().publisher and Multi.createFrom().safePublisher, return that Multi
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromPublisherTest.java
Labels: enhancement, backport

#1143 When using `Multi.createFrom().publisher` and `Multi.createFrom().safePublisher` with a Multi, return that Multi directly
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiCreate.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCreateFromPublisherTest.java
Labels: enhancement

#1154 Upgrade RevAPI v28
  pom.xml
Labels: dependencies, java

#1162 Upgrade to TestNG 7.7.0
  pom.xml
Labels: dependencies

#1166 Do not check dependencies in RevAPI
  pom.xml
Labels: ci/cd/build
