Repository smallrye/smallrye-mutiny, pull requests merged in 2022-08, with the labels that each got.

#1006 Configure dependabot to track the 1.x branch in addition to the default branch
  .github/dependabot.yml
Labels: ci/cd/build

#1028 Various 1.x branch upgrades
  pom.xml
Labels: dependencies

#1031 Run the Reactive Streams Operators TCK again
  reactive-streams-operators/pom.xml
Labels: bug, ci/cd/build, backport
