Repository smallrye/smallrye-mutiny, pull requests merged in 2022-01, with the labels that each got.

#790 Update Coroutines to 1.6.0, Kotlin API to 1.5 and refactored tests
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/DeferredAsUniTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/FlowAsMultiTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/TestUtil.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/UniAwaitSuspendingTest.kt
  pom.xml
Labels: Kotlin

#794 Profile to run the RS TCK TestNG tests in parallel
  reactive-streams-tck-tests/pom.xml
Labels: ci/cd/build

#797 GitBlameDeprecated: refactor to a blame deprecated / experimental API tool
  .build/BlameAPI.java
Labels: enhancement, ci/cd/build

#796 Round of deprecation removals and misc cleanups ahead of 1.3.0
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiOverflow.java
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiTransform.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniOnTerminate.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/UniCallbackSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/UniAssertSubscriber.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractUni.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiOnCompletionCall.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/multicast/MultiPublishOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniRetryAtMost.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiCollectTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiDistinctTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnOverflowTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectFirstOrLastTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSelectWhereAndWhenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSkipTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiSkipWhereAndWhenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTakeTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiTransformByMergingTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniSubscribeAsCompletionStageTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniToPublisherTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiToHotStreamTest.java
Labels: technical-debt

#798 Uni memoization is not experimental anymore
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/Uni.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniMemoize.java
Labels: enhancement, noteworthy-feature

#802 Remove deprecated RevAPI configuration for filtering and reporting
  implementation/revapi.json
  math/revapi.json
  reactor/revapi.json
  rxjava/revapi.json
  rxjava3/revapi.json
Labels: ci/cd/build

#809 Limit workflow concurrency (main CI/CD + PR check workflows)
  .github/workflows/build-main.yml
  .github/workflows/build-pull.yml
Labels: ci/cd/build

#813 Mention the REBLS paper
  README.adoc
  documentation/src/main/jekyll/pages/philosophy.adoc
Labels: documentation

#815 Fix RevAPI filtering new syntax
  implementation/revapi.json
  math/revapi.json
  reactor/revapi.json
  rxjava/revapi.json
  rxjava3/revapi.json
Labels: bug, ci/cd/build

#817 MultiOnRetry is ignoring the onFailure predicate
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRetryOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiRetryWhenOp.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniRetryAtMost.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryUntilTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryWhenTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniOnFailureRetryUntilTest.java
Labels: bug

#819 Reduce MutinySchedulerTest flakiness in CI
  implementation/src/main/java/io/smallrye/mutiny/infrastructure/Infrastructure.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/MutinySchedulerTest.java
Labels: ci/cd/build

#824 Fix a Kotlin test timing issue due to slow starting coroutines
  kotlin/pom.xml
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/FlowAsMultiTest.kt
Labels: bug

#825 Limit Uni.join().{all,first}() concurrency
  implementation/pom.xml
  implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinAll.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinFirst.java
  implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
  pom.xml
Labels: enhancement

#829 Limit concurrency in Uni.combine().all()
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroupIterable.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/UniAndCombination.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
Labels: enhancement

#831 Avoid `Uni.join().first(unis).toTerminate()` with a concurrency limit
  implementation/src/main/java/io/smallrye/mutiny/groups/UniJoin.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinAll.java
  implementation/src/main/java/io/smallrye/mutiny/operators/uni/builders/UniJoinFirst.java
  implementation/src/test/java/io/smallrye/mutiny/operators/uni/UniJoinTest.java
Labels: enhancement

#836 JPMS open modules do not export packages
  implementation/revapi.json
  implementation/src/main/module/module-info.java
Labels: bug
