Repository smallrye/smallrye-mutiny, pull requests merged in 2023-04, with the labels that each got.

#1253 Allow {Uni,Multi} retry policies to have an explicit scheduled executor
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiRetry.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRetry.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniOnFailureRetryTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiOnFailureRetryTest.java
Labels: enhancement

#1255 Fix the AssertSubscriber.assertItems error message
  implementation/src/main/java/io/smallrye/mutiny/helpers/test/AssertionHelper.java
  implementation/src/test/java/io/smallrye/mutiny/helpers/test/AssertSubscriberTest.java
Labels: bug, backport

#1257 Simplify the MultiSubscribe operator implementation
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiSubscribeOnOp.java
Labels: technical-debt

#1261 Emit empty list when grouping item by time windows and no item in the window
  implementation/revapi.json
  implementation/src/main/java/io/smallrye/mutiny/groups/MultiGroupIntoLists.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/MultiBufferWithTimeoutOp.java
  implementation/src/test/java/io/smallrye/mutiny/operators/MultiGroupTest.java
Labels: enhancement

#1263 Fix the website deployment artefact awaiting step
  .github/workflows/deploy-site.yml
Labels: ci/cd/build

#1264 Quick Maven build profile
  README.md
  pom.xml
Labels: ci/cd/build

#1265 Include Java 20 in the build matrix
  .github/workflows/build-main.yml
  .github/workflows/build-pull.yml
Labels: ci/cd/build

#1266 Disabling MultiConcatMapNoPrefetchTest in CI until 1254 has been fixed
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/MultiConcatMapNoPrefetchTest.java
Labels: bug, ci/cd/build
