Repository smallrye/smallrye-mutiny, pull requests merged in 2023-09, with the labels that each got.

#1356 Rename UniMemoize#atLeast to forFixedDuration
  implementation/src/main/java/io/smallrye/mutiny/groups/UniMemoize.java
  implementation/src/test/java/io/smallrye/mutiny/groups/UniMemoizeTest.java
Labels: enhancement

#1360 Fix description of the UniRepeat::whilst method
  implementation/src/main/java/io/smallrye/mutiny/groups/UniRepeat.java
Labels: documentation

#1362 refactor: reworked Uni combination APIs
  .build/WaitForCentral.java
  context-propagation/src/test/java/io/smallrye/mutiny/context/UniContextPropagationTest.java
  documentation/src/test/java/guides/operators/CombiningItemsTest.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup2.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup3.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup4.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup5.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup6.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup7.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup8.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroup9.java
  implementation/src/main/java/io/smallrye/mutiny/groups/UniAndGroupIterable.java
  implementation/src/test/java/io/smallrye/mutiny/infrastructure/MutinySchedulerTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniAndTest.java
  implementation/src/test/java/io/smallrye/mutiny/operators/UniZipTest.java
Labels: enhancement

#1370 docs: add a workshop example for Multi::split
  workshop-examples/src/main/java/_07_advanced_streaming/_01_Multi_Split.java
  workshop-examples/src/main/java/_08_misc/_01_Multi_Custom_Operator.java
  workshop-examples/src/main/java/_08_misc/_02_Logging.java
  workshop-examples/src/main/java/_08_misc/_03_Context.java
Labels: documentation

#1369 docs: document how to express branching in a pipeline
  documentation/docs/guides/branching.md
  documentation/mkdocs.yml
  documentation/src/test/java/guides/BranchingTest.java
  workshop-examples/src/main/java/_03_composition_transformation/_20_Uni_Branching.java
  workshop-examples/src/main/java/_03_composition_transformation/_21_Multi_Branching.java
Labels: documentation

#1361 Modernize the release workflows
  .build/bump-to-next-version.sh
  .build/bump-to-release-version.sh
  .build/clear-revapi-justifications.sh
  .build/deploy-snapshot.sh
  .build/justfile-for-release
  .build/release-with-jreleaser.sh
  .build/setup-git.sh
  .build/setup-jbang.sh
  .github/workflows/build-1.x.yml
  .github/workflows/build-main.yml
  .github/workflows/build-pull-1.x.yml
  .github/workflows/build-pull.yml
  .github/workflows/deploy-release.yml
  .github/workflows/deploy-site.yml
  .github/workflows/post-release.yml
  .github/workflows/prepare-release.yml
  .github/workflows/release.yml
  pom.xml
Labels: ci/cd/build

#1374 Release CI enhancements after 2.5.0-M1
  .build/justfile-for-release
  .github/workflows/build-main.yml
  .github/workflows/push-release-to-maven-central.yml
  pom.xml
Labels: ci/cd/build

#1375 CI Fixes after 2.5.0-M2
  .build/justfile-for-release
  .github/workflows/push-release-to-maven-central.yml
  .github/workflows/release.yml
Labels: ci/cd/build

#1376 JReleaser refinements
  pom.xml
Labels: ci/cd/build

#1384 build(maven): use the Jandex Maven plugin from SmallRye rather than JBoss
  implementation/pom.xml
  math/pom.xml
  pom.xml
Labels: ci/cd/build

#1385 feat(maven): generate and attach CycloneDX SBOM to the project artifacts
  implementation/pom.xml
  kotlin/pom.xml
  math/pom.xml
  pom.xml
  reactor/pom.xml
  rxjava3/pom.xml
Labels: enhancement, noteworthy-feature
