Repository smallrye/smallrye-mutiny, pull requests merged in 2023-07, with the labels that each got.

#1313 Documentation: insist on merging vs concatenating order semantics
  documentation/docs/tutorials/transforming-items-asynchronously.md
Labels: documentation

#1309 Multi split operator
  documentation/Pipfile.lock
  documentation/docs/guides/multi-split.md
  documentation/mkdocs.yml
  documentation/src/test/java/guides/operators/SplitTest.java
  implementation/pom.xml
  implementation/src/main/java/io/smallrye/mutiny/Multi.java
  implementation/src/main/java/io/smallrye/mutiny/operators/AbstractMulti.java
  implementation/src/main/java/io/smallrye/mutiny/operators/multi/split/MultiSplitter.java
  implementation/src/main/java/module-info.java
  implementation/src/test/java/io/smallrye/mutiny/operators/multi/split/MultiSplitterTest.java
  reactive-streams-tck-tests/src/test/java/io/smallrye/mutiny/tcktests/MultiSplitTckTest.java
Labels: enhancement, noteworthy-feature

#1323 Issue #1316: Kotlin - Remove unnecessary suspend modifier from asFlow and Uni builder
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Multi.kt
  kotlin/src/main/kotlin/io/smallrye/mutiny/coroutines/Uni.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/MultiAsFlowTest.kt
  kotlin/src/test/kotlin/io/smallrye/mutiny/coroutines/UniCoroutineBuilderTest.kt
Labels: enhancement
